// ===== FILE: src/domain/catalog/syndicates/vendorEntries/nightwave.ts =====
import { SY } from "../../../ids/syndicateIds";
import type { SyndicateVendorEntry } from "../syndicateVendorCatalog";

/**
 * Nightwave:
 * - 30 ranks, earned via Nightwave acts (no sacrifice / rank-up purchase costs).
 * - Offerings are purchased with Nightwave Cred.
 * - Everything except "Always Available" Rotates in/out.
 */
export const NIGHTWAVE_VENDOR_ENTRY: SyndicateVendorEntry = {
    id: SY.NIGHTWAVE,
    name: "Nightwave",

    // Nightwave ranks are earned, not purchased.
    // We keep these as empty-cost ranks so the UI can still render the rank ladder consistently.
    rankUps: [
    ],
    rankInfo: "Nightwave has 30 Ranks with 150 Prestige Ranks earning 15 Credits per Prestige Rank.",

    offerings: [
        // Rotating offerings (everything except "Always Available")

        // Auras (20 cred each)
        { name: "Corrosive Projection", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Aura (Temporary)" },
        { name: "Dead Eye", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Aura (Temporary)" },
        { name: "Dreamer's Bond", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Aura (Temporary)" },
        { name: "EMP Aura", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Aura (Temporary)" },
        { name: "Enemy Radar", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Aura (Temporary)" },
        { name: "Energy Siphon", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Aura (Temporary)" },
        { name: "Holster Amp", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Aura (Temporary)" },
        { name: "Infested Impedance", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Aura (Temporary)" },
        { name: "Loot Detector", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Aura (Temporary)" },
        { name: "Physique", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Aura (Temporary)" },
        { name: "Pistol Scavenger", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Aura (Temporary)" },
        { name: "Rejuvenation", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Aura (Temporary)" },
        { name: "Rifle Amp", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Aura (Temporary)" },
        { name: "Rifle Scavenger", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Aura (Temporary)" },
        { name: "Shield Disruption", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Aura (Temporary)" },
        { name: "Shotgun Scavenger", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Aura (Temporary)" },
        { name: "Sniper Scavenger", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Aura (Temporary)" },
        { name: "Sprint Boost", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Aura (Temporary)" },
        { name: "Steel Charge", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Aura (Temporary)" },

        // Weapon Blueprints (50 cred each)
        { name: "Ceramic Dagger Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 50 }], notes: "Blueprint (Temporary)" },
        { name: "Dark Dagger Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 50 }], notes: "Blueprint (Temporary)" },
        { name: "Dark Sword Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 50 }], notes: "Blueprint (Temporary)" },
        { name: "Glaive Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 50 }], notes: "Blueprint (Temporary)" },
        { name: "Heat Dagger Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 50 }], notes: "Blueprint (Temporary)" },
        { name: "Heat Sword Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 50 }], notes: "Blueprint (Temporary)" },
        { name: "Jaw Sword Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 50 }], notes: "Blueprint (Temporary)" },
        { name: "Pangolin Sword Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 50 }], notes: "Blueprint (Temporary)" },
        { name: "Plasma Sword Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 50 }], notes: "Blueprint (Temporary)" },

        // Weapon Augments (20 cred each)
        { name: "Ambush Optics", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Weapon Augment (Temporary)" },
        { name: "Brain Storm", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Weapon Augment (Temporary)" },
        { name: "Bursting Mass", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Weapon Augment (Temporary)" },
        { name: "Critical Mutation", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Weapon Augment (Temporary)" },
        { name: "Critical Precision", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Weapon Augment (Temporary)" },
        { name: "Combat Reload", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Weapon Augment (Temporary)" },
        { name: "Deadly Maneuvers", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Weapon Augment (Temporary)" },
        { name: "Directed Convergence", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Weapon Augment (Temporary)" },
        { name: "Dizzying Rounds", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Weapon Augment (Temporary)" },
        { name: "Double Tap", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Weapon Augment (Temporary)" },
        { name: "Efficient Beams", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Weapon Augment (Temporary)" },
        { name: "Exposing Harpoon", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Weapon Augment (Temporary)" },
        { name: "Eximus Advantage", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Weapon Augment (Temporary)" },
        { name: "Focused Acceleration", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Weapon Augment (Temporary)" },
        { name: "Metamorphic Magazine", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Weapon Augment (Temporary)" },
        { name: "Napalm Grenades", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Weapon Augment (Temporary)" },
        { name: "Photon Overcharge", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Weapon Augment (Temporary)" },
        { name: "Precision Strike", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Weapon Augment (Temporary)" },
        { name: "Range Advantage", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Weapon Augment (Temporary)" },
        { name: "Sentient Barrage", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Weapon Augment (Temporary)" },
        { name: "Shrapnel Rounds", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Weapon Augment (Temporary)" },
        { name: "Skull Shots", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Weapon Augment (Temporary)" },
        { name: "Spring-Loaded Broadhead", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Weapon Augment (Temporary)" },
        { name: "Volatile Variant", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Weapon Augment (Temporary)" },
        { name: "Wild Frenzy", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Weapon Augment (Temporary)" },

        // Warframe Augments (20 cred each)
        { name: "Deceptive Bond", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Warframe Augment (Temporary)" },
        { name: "Purging Slash", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Warframe Augment (Temporary)" },
        { name: "Purifying Flames", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Warframe Augment (Temporary)" },
        { name: "Power of Three", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Warframe Augment (Temporary)" },
        { name: "Prism Guard", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Warframe Augment (Temporary)" },
        { name: "Recharge Barrier", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Warframe Augment (Temporary)" },
        { name: "Rumbled", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Warframe Augment (Temporary)" },
        { name: "Singularity", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 20 }], notes: "Warframe Augment (Temporary)" },

        // Alternate Helmets Blueprints (35 cred each)
        { name: "Ash Locust Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Ash Scorpion Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Atlas Shikoro Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Atlas Tartarus Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Banshee Chorus Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Banshee Reverb Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Baruuk Meroe Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Caliban Cranion Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Chroma Amaru Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Chroma Drac Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Citrine Kalite Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Cyte-09 Espricor Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Dagath Ganceann Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Dante Cantist Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Ember Backdraft Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Ember Phoenix Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Equinox Clisthert Helm Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Equinox Solstice Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Excalibur Avalon Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Excalibur Mordred Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Excalibur Pendragon Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Frost Aurora Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Frost Squall Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Gara Virago Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Garuda Bathory Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Gauss Mag Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Grendel Glutt Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Gyre Automaton Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Harrow Crucis Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Harrow Suffragan Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Hildryn Asuron Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Hydroid Ketos Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Hydroid Triton Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Inaros Anubis Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Inaros Canopic Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Ivara Loxley Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Ivara Zirastra Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Jade Aureolt Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Khora Delphi Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Koumei Orihime Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Kullervo Usvah Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Lavos Cordatus Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Limbo Aristeas Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Limbo Magrite Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Loki Enigma Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Loki Essence Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Loki Swindle Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Mag Coil Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Mag Gauss Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Mesa Longhorn Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Mesa Ovis Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Mirage Harlequin Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Mirage Trivelin Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Nekros Raknis Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Nekros Shroud Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Nezha Circa Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Nezha Jinza Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Nidus Myxini Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Nidus Prion Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Nova Flux Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Nova Quantum Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Nova Slipstream Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Nyx Menticide Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Nyx Vespa Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Oberon Markhor Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Oberon Oryx Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Octavia Cadenza Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Oraxia Chelicera Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Protea Mavv Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Protea Telema Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Qorvex Raxpart Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Revenant Vania Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Rhino Thrak Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Rhino Vanguard Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Saryn Chlora Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Saryn Hemlock Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Sevagoth Lucifuge Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Styanax Agogean Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Styanax Synmora Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Styanax Gerousic Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Temple Rockett Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Titania Aurai Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Titania Mab Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Trinity Aura Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Trinity Meridian Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Valkyr Bastet Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Valkyr Kara Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Vauban Armistice Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Vauban Esprit Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Vauban Gambit Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Volt Pulse Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Volt Storm Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Voruna Anukas Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Wisp Gaoth Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Wukong Dasheng Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Wukong Macak Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Xaku Kintsu Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Yareli Physalia Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Zephyr Cierzo Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },
        { name: "Zephyr Tengu Helmet Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Alt Helmet Blueprint (Temporary)" },

        // Weapon Skin Blueprints (various cred costs)
        { name: "Atomos Solstice Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Arca Plasmor Solstice Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Atterax Desert-Camo Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Burston Solstice Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Corinth Solstice Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Dual Keres Solstice Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Dual Zoren Dagger-Axe Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Exergis Shock-Camo Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Falcor Shock-Camo Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Fragor Brokk Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Fulmin Solstice Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Galatine Solstice Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Grinlok Desert-Camo Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Gram Solstice Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Guandao Solstice Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Guandao Synoid Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Hek Desert-Camo Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Ignis Solstice Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Karak Desert-Camo Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Lenz Solstice Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Marelok Desert-Camo Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Plinx Shock-Camo Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Pyrana Synoid Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Rubico Synoid Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Scindo Dagger-Axe Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Scindo Manticore Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Scindo Solstice Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Tatsu Solstice Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 35 }], notes: "Weapon Skin Blueprint (Temporary)" },
        { name: "Tonkor Desert-Camo Skin Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "Weapon Skin Blueprint (Temporary)" },

        // Decorations (Ornaments/Floofs/Noggles/Posters/Other)
        { name: "Nightwave Ornament", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 40 }], notes: "Decoration (Temporary)" },
        { name: "Saturn Six Ornament", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 40 }], notes: "Decoration (Temporary)" },
        { name: "Emissary Ornament", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 40 }], notes: "Decoration (Temporary)" },
        { name: "Glassmaker Ornament", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 40 }], notes: "Decoration (Temporary)" },

        { name: "Gral's Tusk Thumper Bull Floof", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 40 }], notes: "Floof (Temporary)" },
        { name: "Gral's Kubrodon Floof", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 40 }], notes: "Floof (Temporary)" },
        { name: "Gral's Pobber Floof", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 40 }], notes: "Floof (Temporary)" },

        { name: "Noggle Statue - The Wolf", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 40 }], notes: "Noggle (Temporary)" },
        { name: "Ember Vermillion Noggle", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 40 }], notes: "Noggle (Temporary)" },

        { name: "Hero of Duviri Display", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 40 }], notes: "Poster/display (Temporary)" },

        { name: "Kinetic Siphon Trap Decoration", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 40 }], notes: "Decoration (Temporary)" },
        { name: "Nihil's Oubliette", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 60 }], notes: "Decoration (Temporary)" },

        // Other (armor/emblems/glyphs/sigils/gear/emotes/palettes/Scrawls/syandanas/captura)
        { name: "Saturn Six Chest Plate", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 75 }], notes: "Cosmetic armor (Temporary)" },
        { name: "Saturn Six Arm Plates", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 75 }], notes: "Cosmetic armor (Temporary)" },
        { name: "Saturn Six Knee Plates", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 75 }], notes: "Cosmetic armor (Temporary)" },

        { name: "Emissary Emblem", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "Emblem (Temporary)" },
        { name: "Glassmaker Emblem", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "Emblem (Temporary)" },
        { name: "Saturn Six Emblem", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "Emblem (Temporary)" },

        { name: "Contrathermal Companion Glyph", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "Glyph (Temporary)" },
        { name: "Nora Night Glyph Pack", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 45 }], notes: "Glyph pack (Temporary)" },
        { name: "Wolf of Saturn Six Glyph - Light", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "Glyph (Temporary)" },
        { name: "Wolf of Saturn Six Glyph - Dark", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "Glyph (Temporary)" },

        { name: "Emissary Sigil", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "Sigil (Temporary)" },
        { name: "Glassmaker Sigil", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "Sigil (Temporary)" },
        { name: "Nightwave Sigil", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "Sigil (Temporary)" },
        { name: "Orowyrm's Rage Sigil", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "Sigil (Temporary)" },
        { name: "Saturn Six Sigil", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "Sigil (Temporary)" },

        { name: "Wolf Beacon", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 50 }], notes: "Gear item (Temporary)" },
        { name: "Wolf Howl Emote", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 50 }], notes: "Emote (Temporary)" },
        { name: "Gamma", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 100 }], notes: "Color palette (Temporary)" },

        { name: "Ancient K-Drive Scrawl", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "K-Drive Scrawl (Temporary)" },
        { name: "Wolf K-Drive Scrawl", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 30 }], notes: "K-Drive Scrawl (Temporary)" },

        { name: "Saturn Six Syandana", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 75 }], notes: "Syandana (Temporary)" },
        { name: "Saturn Six Scene", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 45 }], notes: "Captura Scene (Temporary)" },

        // Always Available (non-rotating)
        { name: "Nitain Extract (x5)", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 15 }], notes: "Permanent" },
        { name: "Kuva (10,000)", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 50 }], notes: "Permanent" },

        { name: "Orokin Catalyst", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 75 }], notes: "Built (Permanent)" },
        { name: "Orokin Reactor", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 75 }], notes: "Built (Permanent)" },

        { name: "Vauban Chassis Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 25 }], notes: "Blueprint (Permanent)" },
        { name: "Vauban Neuroptics Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 25 }], notes: "Blueprint (Permanent)" },
        { name: "Vauban Systems Blueprint", rankRequired: 0, costs: [{ kind: "item", name: "Nightwave Cred", qty: 25 }], notes: "Blueprint (Permanent)" }
    ]
};
