export const ITEMS_LEAN_DATA_FIELDS = [
    "Icon",
    "MarketMode",
    "RegularPrice",
    "PremiumPrice",
    "ShowInMarket",
    "ProductCategory",
    "resultItemType",
    "ResultItem",
    "type",
    "CompatibilityTags",
    "WeaponTypes",
    "ArtifactSlots",
] as const;

export const WARFRAME_ALL_TOP_LEVEL_FIELDS = [
    "uniqueName",
    "name",
    "category",
    "type",
    "compatName",
    "rarity",
    "baseDrain",
    "fusionLimit",
    "isExilus",
    "isAugment",
    "isUtility",
    "isPrime",
    "imageName",
    "introduced",
    "releaseDate",
    "tradable",
    "transmutable",
    "description",
    "modSet",
    "modSetValues",
    "polarity",
    "wikiaThumbnail",
    "wikiaUrl",
    "masteryReq",
    "vaulted",
    "vaultDate",
    "health",
    "shield",
    "armor",
    "power",
    "sprintSpeed",
    "polarities",
    "aura",
    "exalted",
    "damage",
    "totalDamage",
    "criticalChance",
    "criticalMultiplier",
    "procChance",
    "statusChance",
    "fireRate",
    "magazineSize",
    "reloadTime",
    "accuracy",
    "multishot",
    "noise",
    "trigger",
    "slot",
    "disposition",
    "omegaAttenuation",
    "range",
    "followThrough",
    "comboDuration",
    "heavyAttackDamage",
    "slamAttack",
    "slideAttack",
    "stancePolarity",
    "stamina",
    "marketCost",
    "productCategory",
    "tags",
    "ducats",
] as const;

export const WARFRAME_ALL_COMPONENT_FIELDS = [
    "uniqueName",
    "name",
    "itemCount",
    "drops",
] as const;

export const WARFRAME_ALL_COLLECTION_FIELDS = [
    "levelStats",
    "drops",
    "components",
    "abilities",
    "attacks",
] as const;
